### PR TITLE
Fixed assert on platforms with different sort rules (#728)

### LINKED ISSUE #728: Tests do not run reliably on Windows
The underlying problem appears to be assuming the output of `readdirSync()` is sorted according to ASCII order, so that `assertSorted()` throws in `DiskFS.prototype.readdir` (in `get-definitely-typed.ts`). The specific case is `babel__code-frame` vs. `babelify`.

Adding a `sort()` fixes the issue. I'll be submitting a PR, just creating this issue for tracking purposes.

### PR DESCRIPTION
**Pull request by doug-a-brunner**
Fixes #728.

### CODE REVIEW

File: src/get-definitely-typed.ts [hunk 1]
```diff
@@ -225,7 +225,7 @@ class DiskFS implements FS {
     }
 
     readdir(dirPath?: string): ReadonlyArray<string> {
-        return assertSorted(readdirSync(this.getPath(dirPath))).filter(name => name !== ".DS_STORE");
+        return assertSorted(readdirSync(this.getPath(dirPath)).sort()).filter(name => name !== ".DS_STORE");
```
Comment (sandersn) [inline src/get-definitely-typed.ts]: Can you get rid of the `assertSorted` call? Now, it's just testing that `sort` works.

Comment (doug-a-brunner) [reply src/get-definitely-typed.ts]: Done.
